#!/bin/bash
echo 'Best School' > '*\\\'"Best School"\'\\*$?\*\*\*\*\*:)' ; echo '' >> '*\\\'"Best School"\'\\*$?\*\*\*\*\*:)' ; echo "File '*\\'\"Best School\"'\\*\$?\*\*\*\*\*:)' created successfully."


